### ISSUE TITLE
Captcha not checked in time

### ISSUE THREAD

**Issue by AbhinavMishra32** [GaspardCulis/elevenlabs-unleashed#19]
Error:
> (venv) PS F:\A\Gits\elevenlabs-unleashed> python .\script.py
> Traceback (most recent call last):
>   File "F:\A\Gits\elevenlabs-unleashed\script.py", line 3, in <module>
>     username, password, api_key = create_account()
>                                   ^^^^^^^^^^^^^^^^
>   File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\elevenlabs_unleashed\account.py", line 140, in create_account
>     raise Exception("Captcha not checked in time")
> Exception: Captcha not checked in time
> Exception ignored in: <function Chrome.__del__ at 0x0000027882F431A0>
> Traceback (most recent call last):
>   File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
>   File "F:\A\Gits\elevenlabs-unleashed\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
> OSError: [WinError 6] The handle is invalid
> 

My code:
```
from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()

from elevenlabs_unleashed.manager import ELUAccountManager
from elevenlabs import generate, set_api_key, play, api

eluac = ELUAccountManager(set_api_key, nb_accounts= 2) # Creates a queue of API keys
eluac.next() # First call will block the thread until keys are generated, and call set_api_key

def speak(self, message: str):
    try:
        audio = generate(
            text=message,
            voice="Josh", # I like this one
            model="eleven_multilingual_v1"
        )
    except elevenlabs.api.error.RateLimitError as e:
        print("[ElevenLabs] Maximum number of requests reached. Getting a new API key...")
        eluac.next() # Uses next API key in queue, should be instant as nb_accounts > 1, and will generate a new key in a background thread.
        speak(message)
        return

    print("[ElevenLabs] Starting the stream...")
    play(audio)


from elevenlabs_unleashed.tts import UnleashedTTS

tts = UnleashedTTS(nb_accounts=2, create_accounts_threads=2)
"""
Will automatically generate 2 accounts in 2 threads. Takes a few seconds.
"""

tts.speak("Hello world!", voice="Josh", model="eleven_multilingual_v1")
```

**Comment by GaspardCulis** [comment]
Hey! Check out the [other issues](https://github.com/GaspardCulis/elevenlabs-unleashed/issues/15) to better understand in what state the project is currently in.
