### ISSUE TITLE
names not found

### ISSUE THREAD

**Issue by Bvhhhy** [GaspardCulis/elevenlabs-unleashed#7]
Traceback (most recent call last):
  File "D:\python\j.py", line 1, in <module>
    from elevenlabs_unleashed.manager import ELUAccountManager
  File "D:\python\lib\site-packages\elevenlabs_unleashed\manager.py", line 2, in <module>
    from elevenlabs_unleashed.account import create_account
  File "D:\python\lib\site-packages\elevenlabs_unleashed\account.py", line 2, in <module>
    import names
ModuleNotFoundError: No module named 'names'

**Comment by GaspardCulis** [comment]
You didn't installed the dependencies with pip as specified in the readme
```bash
pip install -r requirements.txt
```
